# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Awards"
  url = "#awards"
  weight = 50

[[main]]
  name = "Portfolio"
  url = "#portfolio"
  weight = 60

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 70

[[main]]
  name = "Blog"
  url = "https://scarlettyellow.github.io/"
  weight = 80

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 130

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]   
  name = "CV"
  url = "https://www.scarletthuang.cn"
  weight = 120
